// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rollcall.Repositories;

#nullable disable

namespace rollcall.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220514145607_PolishCollationv2")]
    partial class PolishCollationv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rollcall.Models.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Rollcall.Models.ChildMeal", b =>
                {
                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("MealName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Attendance")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ChildId", "MealName", "Date");

                    b.HasIndex("MealName");

                    b.ToTable("ChildAttendance");
                });

            modelBuilder.Entity("Rollcall.Models.DefaultMeal", b =>
                {
                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("MealName")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Attendance")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ChildId", "MealName");

                    b.HasIndex("MealName");

                    b.ToTable("DefaultAttendance");
                });

            modelBuilder.Entity("Rollcall.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Rollcall.Models.GroupMask", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("MealName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("Attendance")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("GroupId", "MealName", "Date");

                    b.HasIndex("MealName");

                    b.ToTable("GroupAttendance");
                });

            modelBuilder.Entity("Rollcall.Models.MealSchema", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Name");

                    b.ToTable("MealSchemas");

                    b.HasData(
                        new
                        {
                            Name = "breakfast"
                        },
                        new
                        {
                            Name = "dinner"
                        },
                        new
                        {
                            Name = "desert"
                        });
                });

            modelBuilder.Entity("Rollcall.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rollcall.Models.Child", b =>
                {
                    b.HasOne("Rollcall.Models.Group", "MyGroup")
                        .WithMany("Children")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyGroup");
                });

            modelBuilder.Entity("Rollcall.Models.ChildMeal", b =>
                {
                    b.HasOne("Rollcall.Models.Child", "TargetChild")
                        .WithMany("DailyMeals")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rollcall.Models.MealSchema", "Schema")
                        .WithMany()
                        .HasForeignKey("MealName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");

                    b.Navigation("TargetChild");
                });

            modelBuilder.Entity("Rollcall.Models.DefaultMeal", b =>
                {
                    b.HasOne("Rollcall.Models.Child", "TargetChild")
                        .WithMany("DefaultMeals")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rollcall.Models.MealSchema", "Schema")
                        .WithMany()
                        .HasForeignKey("MealName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");

                    b.Navigation("TargetChild");
                });

            modelBuilder.Entity("Rollcall.Models.GroupMask", b =>
                {
                    b.HasOne("Rollcall.Models.Group", "TargetGroup")
                        .WithMany("Masks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rollcall.Models.MealSchema", "Schema")
                        .WithMany()
                        .HasForeignKey("MealName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schema");

                    b.Navigation("TargetGroup");
                });

            modelBuilder.Entity("Rollcall.Models.Child", b =>
                {
                    b.Navigation("DailyMeals");

                    b.Navigation("DefaultMeals");
                });

            modelBuilder.Entity("Rollcall.Models.Group", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Masks");
                });
#pragma warning restore 612, 618
        }
    }
}
