// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rollcall.Repositories;

#nullable disable

namespace rollcall.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Rollcall.Models.Attendance", b =>
                {
                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Meals")
                        .HasColumnType("int");

                    b.HasKey("ChildId", "Date");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("Rollcall.Models.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DefaultMeals")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("Rollcall.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Rollcall.Models.Mask", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Meals")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "Date");

                    b.ToTable("Masks");
                });

            modelBuilder.Entity("Rollcall.Models.MealSchema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MealSchemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "dinner"
                        },
                        new
                        {
                            Id = 3,
                            Name = "desert"
                        });
                });

            modelBuilder.Entity("Rollcall.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rollcall.Models.Attendance", b =>
                {
                    b.HasOne("Rollcall.Models.Child", "TargetChild")
                        .WithMany("MyAttendance")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetChild");
                });

            modelBuilder.Entity("Rollcall.Models.Child", b =>
                {
                    b.HasOne("Rollcall.Models.Group", "MyGroup")
                        .WithMany("Children")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyGroup");
                });

            modelBuilder.Entity("Rollcall.Models.Mask", b =>
                {
                    b.HasOne("Rollcall.Models.Group", "MaskedGroup")
                        .WithMany("Masks")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaskedGroup");
                });

            modelBuilder.Entity("Rollcall.Models.Child", b =>
                {
                    b.Navigation("MyAttendance");
                });

            modelBuilder.Entity("Rollcall.Models.Group", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Masks");
                });
#pragma warning restore 612, 618
        }
    }
}
